# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: o:/ENGS31/final/final.srcs/sources_1/ip/BRAM/BRAM.xci
# IP: The module: 'BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/ENGS31/final/final.srcs/sources_1/ip/BRAM/BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: o:/ENGS31/final/final.srcs/sources_1/ip/BRAM/BRAM.xci
# IP: The module: 'BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/ENGS31/final/final.srcs/sources_1/ip/BRAM/BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
