# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir O:/ENGS31/final/final.cache/wt [current_project]
set_property parent.project_path O:/ENGS31/final/final.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
add_files -quiet o:/ENGS31/final/final.srcs/sources_1/ip/BRAM/BRAM.dcp
set_property used_in_implementation false [get_files o:/ENGS31/final/final.srcs/sources_1/ip/BRAM/BRAM.dcp]
read_vhdl -library xil_defaultlib {
  O:/ENGS31/final/final.srcs/sources_1/imports/sources_1/imports/Downloads/debouncer.vhd
  O:/ENGS31/final/final.srcs/sources_1/imports/sources_1/new/knobdecoder.vhd
  O:/ENGS31/final/final.srcs/sources_1/imports/sources_1/new/VGA_SYNC.vhd
  O:/ENGS31/final/final.srcs/sources_1/imports/sources_1/new/Mux2x1.vhd
  O:/ENGS31/final/final.srcs/sources_1/imports/sources_1/imports/new/ColorDecoder.vhd
  O:/ENGS31/final/final.srcs/sources_1/imports/sources_1/new/cwController.vhd
  O:/ENGS31/final/final.srcs/sources_1/imports/sources_1/new/CurPixel.vhd
  O:/ENGS31/final/final.srcs/sources_1/new/kctest_top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc O:/ENGS31/final/final.srcs/constrs_1/imports/ENGS31/Basys3_Master.xdc
set_property used_in_implementation false [get_files O:/ENGS31/final/final.srcs/constrs_1/imports/ENGS31/Basys3_Master.xdc]


synth_design -top kct_TOP -part xc7a35tcpg236-1


write_checkpoint -force -noxdef kct_TOP.dcp

catch { report_utilization -file kct_TOP_utilization_synth.rpt -pb kct_TOP_utilization_synth.pb }
